create table users
(
    id                      bigint generated by default as identity
        primary key,
    email                   varchar(255),
    password                varchar(255),
    enabled                 boolean,
    verification_code       varchar(255),
    verification_expiraion  timestamp with time zone,
    verification_expiration timestamp(6)
);